#!/bin/sh
# see https://help.github.com/articles/changing-author-info/

[ -n "$1" ] && new_name="$1"  || exit 1
[ -n "$2" ] && new_email="$2" || exit 1

[ -n "$3" ] && old_name="$3"  || exit 1
[ -n "$3" ] && old_email="$4" || exit 1

old_name_lower=$(echo "$old_name"   | tr [:upper:] [:lower:])
old_email_lower=$(echo "$old_email" | tr [:upper:] [:lower:])

git filter-branch -f --env-filter '
	git_committer_name=$( echo "$GIT_COMMITTER_NAME"  | tr [:upper:] [:lower:])
	git_committer_email=$(echo "$GIT_COMMITTER_EMAIL" | tr [:upper:] [:lower:])
	if   [ "$git_committer_name"  = "'"$old_name_lower"'"  ] \
		&& [ "$git_committer_email" = "'"$old_email_lower"'" ]
	then
  	export GIT_COMMITTER_NAME="'"$new_name"'"
  	export GIT_COMMITTER_EMAIL="'"$new_email"'"
	fi

	git_author_name=$( echo "$GIT_AUTHOR_NAME"  | tr [:upper:] [:lower:])
	git_author_email=$(echo "$GIT_AUTHOR_EMAIL" | tr [:upper:] [:lower:])
	if   [ "$git_author_name"  = "'"$old_name_lower"'"  ] \
		&& [ "$git_author_email" = "'"$old_email_lower"'" ]
	then
  	export GIT_AUTHOR_NAME="'"$new_name"'"
  	export GIT_AUTHOR_EMAIL="'"$new_email"'"
	fi
' --tag-name-filter cat -- --all
