#!/bin/sh

VERSION='1.0.20180302'

print_help() {
	cat <<-EOF
		Version: $VERSION
		Usage: $(basename -- $0) [<options>] [group] [permissions] [--] <path>
		Options:
		-h, --help     - Display this help screen and exit
		-V, --version  - Display version info and exit
		-g group       - Group to make owner of new repo. Defaults to user's group.
		-p permissions - Group permission, in octal. Defaults to '0600'.
		--             - end of options, path is next
		path           - Paths must not contain newline characters.
	EOF
}

parse_args() {
	# get input options
	while [ $# -gt 0 ]; do
		case "$1" in
			'-h'|'--help'    ) { print_help;       exit; } ;;
			'-V'|'--version' ) { echo "$version";  exit; } ;;
			'-g'             ) { group="$2";      shift; } ;;
			'-p'             ) { permission="$2"; shift; } ;;
			'--'             ) { directory="$2";  break; } ;;
			*                ) { directory="$1";         } ;;
		esac
		shift
	done
	# check directory is specified
	[ -z "$directory"  ] && print_help && exit
	# apply defaults
	[ -z "$group"      ] && group=$(id -ng)
	[ -z "$permission" ] && permission='0600'
}

main() {
	parse_args "$@"
	sudo mkdir -p "$directory"             \
		&& sudo chown -R $group "$directory" \
		&& sudo -u $group git init --bare --shared=$permissions "$directory"
}

main "$@"
