#!/bin/sh
# see https://help.github.com/articles/changing-author-info/

git filter-branch -f --env-filter '
OLD_NAMES="Old Name
Bad Name"

CORRECT_NAME="First Last"
CORRECT_EMAIL="first.last@example.com"

IFS="
"
for OLD_NAME in $OLD_NAMES; do
	OLD_NAME=$(echo $OLD_NAME | tr "[:upper]" "[:lower]")
	GIT_COMMITTER_NAME=$(echo $GIT_COMMITTER_NAME | tr "[:upper]" "[:lower]")
  if [ "$GIT_COMMITTER_NAME" == "$OLD_NAME" ]; then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
  fi
	GIT_AUTHOR_NAME=$(echo $GIT_COMMITTER_NAME | tr "[:upper]" "[:lower]")
  if [ "$GIT_AUTHOR_NAME" == "$OLD_NAME" ]; then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
  fi
done
' --tag-name-filter cat -- --all
#' --tag-name-filter cat -- --branches --tags

git filter-branch -f --env-filter '
OLD_EMAILS="bad_email@example.com
old_email@example.com"

CORRECT_NAME="First Last"
CORRECT_EMAIL="first.last@example.com"

for OLD_EMAIL in $OLD_EMAILS; do
	OLD_EMAIL=$(echo $OLD_EMAIL | tr "[:upper]" "[:lower]")
	GIT_COMMITTER_EMAIL=$(echo $GIT_COMMITTER_EMAIL | tr "[:upper]" "[:lower]")
  if [ "$GIT_COMMITTER_EMAIL" == "$OLD_EMAIL" ]; then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
  fi
	GIT_AUTHOR_EMAIL=$(echo $GIT_COMMITTER_EMAIL | tr "[:upper]" "[:lower]")
  if [ "$GIT_AUTHOR_EMAIL" == "$OLD_EMAIL" ]; then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
  fi
done
' --tag-name-filter cat -- --all
#' --tag-name-filter cat -- --branches --tags
