#!/bin/sh

print_help() {
	cat <<-EOF
	Version: $version
	Usage: $(basename -- $0) [<options>] [group] [permissions] [--] <path>
	Options:
	-h, --help    - Display this help screen and exit
	-V, --version - Display version info and exit
	group         - Group to make owner of new repo. Defaults to user's group.
	permissions   - Group permission, in octal. Defaults to '0600'.
	--            - end of options, path is next
	path          - Paths must not contain newline characters.
	EOF
}

parse_args() {
  group=$(id -ng)
  permission='0600'

	# get input options
while [ $# -gt 0 ]; do
case "$1" in
'-n'|'--name-only'       ) name_only='--name-only'              ;;
'-m'|'--no-modifications') no_modifications='--no-modifications';;
'-h'|'--help'            ) { print_help;      exit;           } ;;
'-V'|'--version'         ) { echo "$version"; exit;           } ;;
'--'                     ) { path_name="$2";  break;          } ;;
*                        ) { path_name="$1";  break;          } ;;
esac
shift
done

directory="$1"
group=$2
permissions=$3
}

sudo mkdir -p "$directory"
sudo chown -R $group "$directory"
sudo -u $group git int --bare --shared=$permissions "$directory"
