#!/bin/sh

# IN: group-id (gid)
users_with_primary_group_id() {
	awk -F':' '{ if ($4 == "'$1'") printf ","$1 }' < /etc/passwd \
		| sed 's/^,//'
}

# OUT: groups with all users
groups_with_users() {
	while read line; do
		users=$(users_with_primary_group_id $(printf $line | awk -F':' '{ print $3 }'))
		printf "${line}$users\n"
	done < /etc/group
}

echo '-----:-:---:-----'
echo 'group:x:gid:users'
echo '-----:-:---:-----'
groups_with_users

